name: Build custom pandoc container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Produce release note
        uses: TriPSs/conventional-changelog-action@v4.0.0
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          version-file: './version_file.json'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ env.REGISTRY }}/wivik/pandoc-plantuml:${{ steps.changelog.outputs.tag }},${{ env.REGISTRY }}/wivik/pandoc-plantuml:latest"
          labels: "${{ env.REGISTRY }}/wivik/pandoc-plantuml:${{ steps.changelog.outputs.tag }},${{ env.REGISTRY }}/wivik/pandoc-plantuml:latest"
          file: Dockerfile
